name: check

on:
  workflow_dispatch:
  schedule:
    - cron: "*/38 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: BeeeQueue/anilist-changelog@dist

      - name: Check git status
        id: status
        run: |
          CHANGED_FILES=$(git diff --name-only -- dist/ action.yml)
          echo "::set-output name=diff-length::${#CHANGED_FILES}"

      - uses: EndBug/add-and-commit@v9
        if: ${{ steps.status.outputs.diff-length > 0 }}
        with:
          message: Update changelog & schema
          default_author: github_actions
          push: true
          add: "schema.graphql CHANGELOG.md"
