name: check

on:
  workflow_dispatch:
  schedule:
    - cron: "*/38 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: BeeeQueue/anilist-changelog@dist

      - name: Set up git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        run: |
          git add .
          git commit -am "Update changelog"

      - name: Push commit
        run: git push
