on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: BeeeQueue/anilist-changelog@main

      - run: git status
