name: ci/cd

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      changed: ${{ steps.status.outputs.diff-length > 0 }}

    steps:
      - uses: actions/checkout@v3

      - run: corepack enable

      - uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: v1-${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            v1-${{ runner.os }}-pnpm-

      - run: pnpm install --frozen-lockfile
        env:
          NODE_ENV: development

      - run: pnpm build

      - name: Check git status
        id: status
        run: |
          CHANGED_FILES=$(git diff --name-only dist/ action.yml)
          echo "::set-output name=diff-length::${#CHANGED_FILES}"

      - name: Compress and archive dist folder
        if: ${{ steps.status.outputs.diff-length > 0 }}
        run: tar -cvf dist.tar.gz dist action.yml

      - name: Upload artifact
        if: ${{ steps.status.outputs.diff-length > 0 }}
        uses: actions/upload-artifact@v3
        with:
          name: dist.tar.gz
          path: dist.tar.gz

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: corepack enable

      - uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: v1-${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            v1-${{ runner.os }}-pnpm-

      - run: pnpm install --frozen-lockfile
        env:
          NODE_ENV: development

      - run: pnpm lint

  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: corepack enable

      - uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: v1-${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            v1-${{ runner.os }}-pnpm-

      - run: pnpm install --frozen-lockfile
        env:
          NODE_ENV: development

      - run: pnpm typecheck

  publish:
    runs-on: ubuntu-latest

    needs: [build, lint, typecheck]
    if: ${{ github.ref == 'refs/heads/main' && needs.build.outputs.changed }}

    steps:
      - uses: actions/checkout@v3
        with:
          ref: dist

      - name: Set up git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Switch to deployment branch
        run: |
          git fetch origin dist
          git switch dist

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist.tar.gz
          path: .

      - name: Extract artifact folder
        run: tar -xvf dist.tar.gz

      - name: Commit changes
        run: |
          git add .
          git commit -am "Publish ${{ github.sha }}"

      - name: Push commit
        run: git push
